---
- hosts: master
  become: true

  vars:
    proxy_env:
      http_proxy: http://10.200.10.1:8118
      https_proxy: http://10.200.10.1:8118
      no_proxy: localhost,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,*.local
    docker_version: 18.09.9.ce
    k8s_version: 1.20.4-00
    node_ip: 192.168.80.10

  tasks:

  # https://docs.projectcalico.org/getting-started/kubernetes/quickstart
  - name: download custom-resources.yaml
    get_url: 
      url: https://docs.projectcalico.org/manifests/custom-resources.yaml
      dest: /home/vagrant/custom-resources.yaml
      validate_certs: no
      mode: '666'

  - name: change owner of custom-resources.yaml to vagrant user
    file:
      path: /home/vagrant/custom-resources.yaml
      owner: vagrant
      group: vagrant
      mode: '666'

  - name: replace CIDR for custom-resources.yaml
    replace:
      path: /home/vagrant/custom-resources.yaml
      regexp: '192.168.0.0/16'
      replace: '172.16.0.0/12'

  - name: Install the Tigera Calico operator
    become: false
    command: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

  - name: Install Calico by creating the necessary custom resource
    become: false
    command: kubectl create -f /home/vagrant/custom-resources.yaml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    become: false
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  - debug:
      msg: "export KUBECONFIG={{ playbook_dir }}/admin.conf"

  - name: fetch admin.conf to local
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: "{{ playbook_dir }}/admin.conf"
      flat: yes

  handlers:
    - name: docker status
      service: name=docker state=started
